# Armored Genesys Cloud CX — Public documentation only. Frame: Google Cloud CCaaS categories (routing, flows/IVR, agent desktop, analytics, quality, workforce).
BOOK=dict(
 title="Armored Genesys Cloud CX",
 subtitle="Advanced practice for contact-centre administrators, supervisors and analysts",
 platform="Genesys",
 sources=[
  ("Genesys Cloud Resource Center","help.mypurecloud.com (Architect, routing, queues, Quality Management, Speech and Text Analytics, Workforce Management, Analytics)"),
  ("Genesys Cloud Developer Center","developer.genesys.cloud (Platform API, Data Actions, integrations)"),
  ("Google Cloud — Contact Center AI Platform documentation","cloud.google.com/contact-center (used only as the reference frame for what a contact-centre platform's concept list contains)"),
 ],
 items=[
 dict(concept="Queue vs skill vs division",stem="A caller needs Spanish billing support in the EMEA business unit. The admin has created a queue called 'Spanish Billing EMEA.' Which constructs should have carried each requirement?",
  opts=[("A queue for billing, a language (Spanish) and/or skill on the interaction, and a division for EMEA's access boundary","KEY"),("Three queues","DROP"),("One skill named 'Spanish Billing EMEA'","INV"),("A division per language","ADJ")],
  target="need · language · unit",deciding="Queues hold work; skills/languages match agents; divisions segment access.",rule="Queue = where. Skill = who can. Division = who may see.",camo=["the queue name"]),
 dict(concept="Routing methods",stem="A queue should first try the customer's previous agent for 30 seconds, then widen to anyone with the skill, then to the whole queue. Which routing configuration?",
  opts=[("Preferred agent routing, then bullseye routing rings that relax skills over time","KEY"),("Standard routing","DROP"),("Conditional group routing only","ADJ"),("Predictive routing","ADJ")],
  target="first · then widen · then everyone",deciding="Bullseye relaxes criteria in timed rings; preferred agent targets a person.",rule="Standard · bullseye · preferred agent · conditional group · predictive — pick by what changes over time.",camo=["30 seconds"]),
 dict(concept="Utilization",stem="An agent is on a voice call and still receives two chats. The supervisor says 'the queue is wrong.' What actually governs this?",
  opts=[("The queue's routing method","ADJ"),("Utilization settings — maximum interactions per media type and which media can interrupt which, at org or agent level","KEY"),("Wrap-up codes","CONF"),("The agent's skill","ADJ")],
  target="on a call AND two chats",deciding="Capacity per media type is utilization.",rule="Utilization decides how many of what an agent can carry at once.",camo=["'the queue is wrong'"]),
 dict(concept="Architect flow types",stem="Four needs: an inbound phone menu; hold-time announcements while waiting in queue; a web chat greeting; a self-service bot. Which Architect flow types?",
  opts=[("Inbound call flow · in-queue call flow · inbound message flow · bot flow","KEY"),("All are inbound call flows","DROP"),("Inbound call · inbound call · inbound message · inbound message","INV"),("Bot flow for all four","ABS")],
  target="menu · while waiting · chat · bot",deciding="Each moment in the journey has its own flow type.",rule="Flow type follows where the customer is and on which channel.",camo=[]),
 dict(concept="Data actions and data tables",stem="An IVR must greet the caller by name from the CRM and route VIPs differently based on a list the business edits weekly. Which Architect building blocks?",
  opts=[("A data action (integration call to the CRM) for the name, and a data table for the VIP list the business maintains","KEY"),("Two data actions","ADJ"),("Hard-code the VIP list in the flow","DROP"),("A skill","CONF")],
  target="from the CRM · list the business EDITS",deciding="External lookups are data actions; editable reference data is a data table.",rule="Data action = call out. Data table = lookup in.",camo=["weekly"]),
 dict(concept="Presence vs routing status",stem="An agent shows 'Available' but receives no interactions. What is the likeliest state?",
  opts=[("Presence is Available but routing status is Off Queue — the agent has not gone On Queue","KEY"),("The queue is closed","ADJ"),("The agent lacks a skill","ADJ"),("Utilization is zero","CONF")],
  target="Available but nothing arrives",deciding="Presence and routing status are separate.",rule="On Queue is the switch; presence is the mood.",camo=[]),
 dict(concept="Wrap-up codes and ACW",stem="Supervisors want to report why customers called, and give agents 45 seconds after each call to finish notes. Which two settings?",
  opts=[("Wrap-up codes assigned to the queue, and after-call work (ACW) configured on the queue with a time limit","KEY"),("Skills and utilization","CONF"),("Evaluation forms","ADJ"),("Scripts","ADJ")],
  target="WHY · 45 seconds after",deciding="Wrap-up = disposition; ACW = time to do it.",rule="Wrap-up codes label; ACW allows.",camo=[]),
 dict(concept="Divisions, roles, permissions",stem="A regional supervisor should see only her region's queues and agents but needs the same permissions as other supervisors. What is configured?",
  opts=[("Assign the supervisor role scoped to her division; objects (queues, users) are placed in that division","KEY"),("A custom role per region","ADJ"),("Remove permissions","DROP"),("A separate org","INV")],
  target="same permissions · only her region",deciding="Roles say what; divisions say where.",rule="Role × division = permission × scope.",camo=[]),
 dict(concept="Quality Management — evaluation forms",stem="Coaches want to score calls on greeting, verification, resolution and empathy, weighted, with a fail-all question on compliance. Which construct?",
  opts=[("An evaluation form with question groups, weights and a critical (fail-all) question, assigned through a quality policy","KEY"),("A survey","CONF"),("Wrap-up codes","ADJ"),("A script","ADJ")],
  target="weighted · fail-all",deciding="Evaluation forms carry weights and critical questions.",rule="Form defines the rubric; policy decides which interactions get it.",camo=[]),
 dict(concept="Quality policies and sampling",stem="Every agent should have three random calls evaluated each week, only calls over two minutes, only from the sales queue. Where is that set?",
  opts=[("A quality policy — conditions (queue, duration), sampling per agent, and the assigned form/evaluator","KEY"),("The evaluation form","ADJ"),("The queue's ACW","CONF"),("Manually by coaches","DROP")],
  target="three · random · per week · conditions",deciding="Policies automate selection.",rule="Policy = which interactions, how many, to whom.",camo=[]),
 dict(concept="Calibration",stem="Two evaluators score the same call 60 and 90. What is the purpose-built remedy?",
  opts=[("A calibration session — multiple evaluators score the same interaction and compare against a reference","KEY"),("Averaging the two scores","DROP"),("Removing one evaluator","INV"),("A new form","ADJ")],
  target="same call · two scores",deciding="Calibration aligns evaluators.",rule="Calibrate people; do not average disagreements away.",camo=[]),
 dict(concept="Speech and Text Analytics — topics and sentiment",stem="Leadership wants to know how often 'cancel my subscription' comes up and how customers feel when it does. Which features, and what is a topic made of?",
  opts=[("Speech and Text Analytics — topics built from phrases that detect the intent, plus sentiment scoring on the transcript","KEY"),("Wrap-up codes","ADJ"),("Evaluation forms","ADJ"),("Predictive routing","CONF")],
  target="how OFTEN · how they FEEL",deciding="Topics detect; sentiment scores.",rule="Topic = phrase set → detection. Sentiment = per-utterance tone → interaction score.",camo=[]),
 dict(concept="Transcription and recording policies",stem="Calls in one queue must be recorded and transcribed and retained for 90 days; another queue must not be recorded at all. Where?",
  opts=[("Recording policies (with conditions per queue) governing recording, transcription and retention","KEY"),("Utilization","CONF"),("The evaluation form","ADJ"),("The agent's presence","CONF")],
  target="this queue yes · that queue no · 90 days",deciding="Policies carry the conditions and the retention.",rule="Recording policy = whether, what, and how long.",camo=[]),
 dict(concept="Workforce Management — forecast, schedule, adherence",stem="A planner needs next month's staffing, then shifts, then to see who was off-plan yesterday. Which three WFM pieces?",
  opts=[("Forecast → schedule → adherence","KEY"),("Schedule → forecast → adherence","INV"),("Adherence → forecast → schedule","INV"),("All three are the same view","DROP")],
  target="next month · shifts · yesterday",deciding="Forecast demand, schedule supply, measure adherence.",rule="Forecast → schedule → adherence, in that order.",camo=[]),
 dict(concept="Performance views vs reports vs API",stem="A supervisor wants a live wallboard; an analyst wants last quarter's handle time by queue in a spreadsheet; a developer wants the same numbers in a data lake. Which routes?",
  opts=[("Performance views (real-time) · exported reports/views (historical) · Analytics API (programmatic)","KEY"),("All from the Analytics API","DROP"),("All from performance views","DROP"),("Reports for all three","ADJ")],
  target="live · last quarter · data lake",deciding="Time horizon and consumer choose the route.",rule="View now, export later, API always.",camo=[]),
 dict(concept="Genesys Cloud Voice vs BYOC",stem="A company wants Genesys to provide phone numbers and carriage; another has a carrier contract and SBCs it must keep. Which telephony options?",
  opts=[("Genesys Cloud Voice for the first; BYOC (Bring Your Own Carrier — cloud or premises) for the second","KEY"),("Both must use Genesys Cloud Voice","ABS"),("Both must use BYOC","ABS"),("Neither needs telephony configuration","ABS")],
  target="provide vs KEEP",deciding="Who owns the carrier decides.",rule="GCV = Genesys carries. BYOC = you carry.",camo=[]),
 dict(concept="Sites, trunks, DIDs",stem="A new office needs its own outbound caller ID, its own emergency address, and numbers routed to its IVR. Which telephony objects?",
  opts=[("A site (location, emergency address, outbound settings), trunk configuration, and DID assignment to the flow","KEY"),("A division","CONF"),("A queue","CONF"),("A skill","CONF")],
  target="caller ID · emergency address · numbers",deciding="Site carries location settings; DIDs map numbers.",rule="Site = where calls originate. DID = which number reaches which flow.",camo=[]),
 dict(concept="External contacts and CRM embedding",stem="Agents want the caller's CRM record to pop on connect, and the interaction logged back. Which mechanisms?",
  opts=[("Screen pop via an integration/embeddable framework (or CRM client) and interaction logging through the integration","KEY"),("A script","ADJ"),("A data table","CONF"),("Manual search","DROP")],
  target="pop on connect · log back",deciding="Embedding does both directions.",rule="Integration = pop in, write back.",camo=[]),
 dict(concept="Scripts",stem="Agents on the retention queue must read a compliance statement and capture three fields in order. Which feature?",
  opts=[("A script assigned to the queue — pages, inputs and variables shown in the interaction panel","KEY"),("A canned response","ADJ"),("A wrap-up code","CONF"),("An evaluation form","ADJ")],
  target="read · capture in order",deciding="Scripts guide the agent during the interaction.",rule="Script = guided conversation; canned response = reusable text.",camo=[]),
 dict(concept="Callbacks",stem="Wait time is 20 minutes; the business wants to offer to call back without losing queue position. Which capability?",
  opts=[("Callback offered from the in-queue flow, scheduled or immediate, retaining queue position","KEY"),("Voicemail","ADJ"),("A second queue","DROP"),("Transfer to an agent","INV")],
  target="without losing POSITION",deciding="Callback is a queued interaction type.",rule="Callback holds the place; voicemail drops it.",camo=[]),
 dict(concept="Secure pause",stem="A caller reads a card number to an agent on a recorded line. What should happen?",
  opts=[("The agent (or an automated trigger) pauses recording — secure pause — for the sensitive portion","KEY"),("Delete the recording after the call","INV"),("Stop recording the whole queue","DROP"),("Nothing; recordings are encrypted","ABS")],
  target="card number on a RECORDED line",deciding="Pause the capture at the moment, not the retention later.",rule="Secure pause protects the segment; deletion after the fact is too late.",camo=[]),
 dict(concept="Knowledge and bots",stem="A self-service bot should answer from curated articles and hand off to an agent with the transcript when it cannot. Which pieces?",
  opts=[("Knowledge workbench articles used by a knowledge/bot flow, with a transfer-to-queue step that carries context","KEY"),("A data table of answers","ADJ"),("An IVR menu","ADJ"),("Canned responses","CONF")],
  target="answer · then hand off WITH transcript",deciding="Knowledge feeds the bot; transfer carries context.",rule="Bot answers; escalation keeps the thread.",camo=[]),
 dict(concept="Agent assist",stem="During a live call the agent should see suggested articles and a running summary without leaving the interaction. Which capability class?",
  opts=[("Agent assist / Agent Copilot — real-time suggestions and summarization in the agent UI","KEY"),("Quality Management","ADJ"),("Workforce Management","CONF"),("Bullseye routing","CONF")],
  target="DURING the call · suggestions",deciding="Real-time assistance is its own capability.",rule="Assist is live; QM is after; WFM is before.",camo=[]),
 dict(concept="Interaction vs conversation",stem="A customer emails, then calls, then chats about the same order. Reporting shows three records. Is that wrong?",
  opts=[("No — each channel session is an interaction; linking them into one customer journey is done through external contacts/journey features, not by merging interactions","KEY"),("Yes — they should be one interaction","INV"),("Yes — chats do not count","ABS"),("No — email is not an interaction","INV")],
  target="three records · same order",deciding="Interaction is per session; journey is the link.",rule="Interactions are atoms; the journey is the molecule.",camo=[]),
 dict(concept="Predictive routing",stem="Routing should match each interaction to the agent most likely to resolve it on first contact, learned from outcomes. Which method, and what does it need?",
  opts=[("Predictive routing — a model trained on historical interaction and outcome data for a chosen KPI, with a fallback routing method","KEY"),("Bullseye","ADJ"),("Preferred agent","ADJ"),("A larger queue","DROP")],
  target="learned from OUTCOMES",deciding="Prediction requires labelled history and a fallback.",rule="Predictive = KPI + history + fallback. It sequences; humans still serve.",camo=[]),
 ])
