#!/usr/bin/env python3
"""One self-contained filing sheet per work. Single source; four outputs."""

import pathlib

HERE = pathlib.Path(__file__).parent

ADDRESS = """```
Library of Congress
U.S. Copyright Office-TX
101 Independence Avenue SE
Washington, DC 20559-6000
```"""

WORKS = [
    dict(
        n=1,
        title="The Atlas of Self — Autobiography Log",
        slug="Filing_1_Atlas_of_Self",
        nature="Text, selection, coordination, and arrangement of literary material.",
        six_a="Text generated by artificial intelligence.",
        six_b="Text, selection, coordination, and arrangement by the author.",
        deposit="Atlas_of_Self.pdf",
        pages=3,
        note=None,
    ),
    dict(
        n=2,
        title="Ouroboros",
        slug="Filing_2_Ouroboros",
        nature="Text (the author's questions), selection, and arrangement.",
        six_a="Answer summaries and annotations generated by artificial intelligence.",
        six_b="The author's questions; selection and arrangement.",
        deposit="Ouroboros.pdf",
        pages=7,
        note=None,
    ),
    dict(
        n=3,
        title="A Framework for Building Her Own Framework",
        slug="Filing_3_Framework_for_Building_Her_Own_Framework",
        nature="Text.",
        six_a=None,
        six_b=None,
        deposit="Kristin_A_Framework_for_Building_Her_Own_Framework.pdf",
        pages=3,
        note="**The strongest work in the batch — wholly human-authored, no AI material.** If only one gets filed, file this one.",
    ),
    dict(
        n=4,
        title="Nursing State — A Traveler's Guide",
        slug="Filing_4_Nursing_State",
        nature="Selection, coordination, and arrangement; text of the underlying framework.",
        six_a="Text generated by artificial intelligence.",
        six_b="Selection, coordination, and arrangement; text of the underlying framework.",
        deposit="Nursing_State_Travelers_Guide.pdf",
        pages=5,
        note=("**Optional — consider holding.** The authorship declaration grades this one **thin**: the expression "
              "is largely AI-drafted, so the claim rests on selection, arrangement, and the underlying framework. "
              "$125 buys a claim the Office may refuse or narrow. Alternatives: fold it into the Atlas as an "
              "arranged entry, or hold it for a human rewrite."),
    ),
]


def sheet(w):
    L = []
    L.append(f"# Filing packet {w['n']} of 4 — {w['title']}")
    L.append("")
    L.append("*Form TX, mailed. Tick as you go. Not legal advice — this is the Copyright Office's own published procedure.*")
    L.append("")
    if w["note"]:
        L.append("> " + w["note"])
        L.append("")
    L.append("## What goes in this envelope — three things, together")
    L.append("")
    L.append("| | Item |")
    L.append("|---|---|")
    L.append("| ☐ | **Form TX**, completed and signed in ink |")
    L.append(f"| ☐ | **Deposit** — `{w['deposit']}` printed, **{w['pages']} pages** |")
    L.append("| ☐ | **Check or money order, $125**, payable to *Register of Copyrights* |")
    L.append("")
    L.append("Nothing else. No cover letter, no service request number, no cash.")
    L.append("")
    L.append("## Form TX — fill exactly this")
    L.append("")
    L.append("| Space | What to write |")
    L.append("|---|---|")
    L.append(f"| **1** Title | `{w['title']}` — must match the deposit's first page exactly |")
    L.append("| **2** Author | Erik Daniel Lindquist |")
    L.append("| **2** Work made for hire? | **No** |")
    L.append("| **2** Citizen of / domiciled in | United States |")
    L.append("| **2** Anonymous / Pseudonymous | **No** / **No** |")
    L.append(f"| **2** Nature of authorship | `{w['nature']}` |")
    L.append("| **3a** Year completed | **2026** |")
    L.append("| **3b** First publication | **leave blank** — this work is unpublished |")
    L.append("| **4** Claimant | Erik Daniel Lindquist, same address |")
    L.append("| **5** Previous registration | **No** |")
    if w["six_a"]:
        L.append(f"| **6a** Preexisting material | `{w['six_a']}` |")
        L.append(f"| **6b** Material added | `{w['six_b']}` |")
    else:
        L.append("| **6a / 6b** | **LEAVE ENTIRELY BLANK.** No AI material and no preexisting material — writing anything here would invent a limitation that does not exist |")
    L.append("| **7** Correspondence | your name, address, email, phone |")
    L.append("| **8** Certification | check **author** · **sign in ink** · date |")
    L.append("| **9** Mail certificate to | your address |")
    L.append("")
    L.append("**Space 3b is the one people get wrong.** Leaving it blank is what makes the work unpublished. Filling it in changes the claim.")
    L.append("")
    L.append("## Address this envelope to")
    L.append("")
    L.append(ADDRESS)
    L.append("")
    L.append("☐ Photograph the packet before sealing.  ☐ Send with tracking.")
    L.append("")
    L.append("## Record")
    L.append("")
    L.append("| | |")
    L.append("|---|---|")
    L.append("| Check no. | |")
    L.append("| Date mailed | |")
    L.append("| Tracking no. | |")
    L.append("| Registration no. (when it arrives) | |")
    L.append("")
    L.append("**The effective registration date is the day the Office receives all three items together.** An incomplete packet does not hold a date — it resets it.")
    L.append("")
    L.append("---")
    L.append("© 2026 Erik Daniel Lindquist. Zone P.")
    L.append("")
    return "\n".join(L)


for w in WORKS:
    (HERE / f"{w['slug']}.md").write_text(sheet(w), encoding="utf-8")
    print("wrote", w["slug"] + ".md")
