#!/usr/bin/env python3
"""Batch 2 filing sheets — packets 5, 6, 7. Same shape as batch 1; one source, three outputs."""

import pathlib

HERE = pathlib.Path(__file__).parent

ADDRESS = """```
Library of Congress
U.S. Copyright Office-TX
101 Independence Avenue SE
Washington, DC 20559-6000
```"""

PROVENANCE = (
    "**Provenance, for the record.** The method predates this employment by decades — the daily observation "
    "report written by hand, the rocket lab with honest error bars, the two-sentence paragraph. Its C213 "
    "application was made **as a student**, solving his own course experience, on his own equipment and his "
    "own time, in Zone P. No employer resources, data, or time are in this work. The claimant states he is "
    "morally, ethically, and legally unconflicted."
)

WORKS = [
    dict(
        n=5,
        title="Guided Mastery — A Framework",
        slug="Filing_5_Guided_Mastery_Framework",
        nature="Text, selection, coordination, and arrangement.",
        six_a="Text generated by artificial intelligence.",
        six_b="The framework, its sequence and rules, and the selection, coordination, and arrangement of the text, by the author.",
        deposit="Guided_Mastery_Framework.md",
        note=("**The anchor work of the batch.** Domain-agnostic: diagnose from real evidence → prioritise by "
              "leverage → breadcrumb the first step → scaffold with immediate feedback → cut camouflage → "
              "transfer-test → build confidence honestly. Nothing institutional is in it."),
    ),
    dict(
        n=6,
        title="Course Mastery Coach — A Framework",
        slug="Filing_6_Course_Mastery_Coach_Framework",
        nature="Text, selection, coordination, and arrangement.",
        six_a="Text generated by artificial intelligence.",
        six_b="The framework, its sequence and rules, and the selection, coordination, and arrangement of the text, by the author.",
        deposit="Course_Mastery_Coach_Framework.md",
        note=("A specialisation of work 5, aimed at competency-based assessment data. Register it in the same "
              "mailing so the pair carries one date."),
    ),
    dict(
        n=7,
        title="Guided Mastery — A Case Study",
        slug="Filing_7_Guided_Mastery_Case_Study",
        nature="Text, selection, coordination, and arrangement.",
        six_a="Text generated by artificial intelligence.",
        six_b="The case, its analysis and results, and the selection, coordination, and arrangement of the text, by the author.",
        deposit="Guided_Mastery_Case_Study.pdf",
        note=("The evidence document — problem, insight, system, results. Carries no institution name, no course "
              "code, and no other person's data."),
    ),
]


def sheet(w):
    L = []
    L.append(f"# Filing packet {w['n']} of 7 — {w['title']}")
    L.append("")
    L.append("*Form TX, mailed. Batch 2. Tick as you go. Not legal advice — this is the Copyright Office's own published procedure.*")
    L.append("")
    L.append("> " + w["note"])
    L.append("")
    L.append(PROVENANCE)
    L.append("")
    L.append("## What goes in this envelope — three things, together")
    L.append("")
    L.append("| | Item |")
    L.append("|---|---|")
    L.append("| ☐ | **Form TX**, completed and signed in ink |")
    L.append(f"| ☐ | **Deposit** — `{w['deposit']}` printed |")
    L.append("| ☐ | **Check or money order, $125**, payable to *Register of Copyrights* |")
    L.append("")
    L.append("Nothing else. No cover letter, no cash.")
    L.append("")
    L.append("## Form TX — fill exactly this")
    L.append("")
    L.append("| Space | What to write |")
    L.append("|---|---|")
    L.append(f"| **1** Title | `{w['title']}` — must match the deposit's first page exactly |")
    L.append("| **2** Author | Erik Daniel Lindquist |")
    L.append("| **2** Work made for hire? | **No** |")
    L.append("| **2** Citizen of / domiciled in | United States |")
    L.append("| **2** Anonymous / Pseudonymous | **No** / **No** |")
    L.append(f"| **2** Nature of authorship | `{w['nature']}` |")
    L.append("| **3a** Year completed | **2026** |")
    L.append("| **3b** First publication | **leave blank** — this work is unpublished |")
    L.append("| **4** Claimant | Erik Daniel Lindquist, same address |")
    L.append("| **5** Previous registration | **No** |")
    L.append(f"| **6a** Preexisting material | `{w['six_a']}` |")
    L.append(f"| **6b** Material added | `{w['six_b']}` |")
    L.append("| **7** Correspondence | your name, address, email, phone |")
    L.append("| **8** Certification | check **author** · **sign in ink** · date |")
    L.append("| **9** Mail certificate to | your address |")
    L.append("")
    L.append("**Space 3b is the one people get wrong.** Leaving it blank is what makes the work unpublished.")
    L.append("")
    L.append("**On Space 6:** the *framework* is the author's — its sequence, its rules, its judgments. The "
             "*sentences* were drafted with AI assistance at his direction, so they are excluded. Claiming the "
             "method while excluding the prose is both accurate and the stronger claim.")
    L.append("")
    L.append("## Address this envelope to")
    L.append("")
    L.append(ADDRESS)
    L.append("")
    L.append("☐ Photograph the packet before sealing.  ☐ Send with tracking.")
    L.append("")
    L.append("## Record")
    L.append("")
    L.append("| | |")
    L.append("|---|---|")
    L.append("| Check no. | |")
    L.append("| Date mailed | |")
    L.append("| Tracking no. | |")
    L.append("| Registration no. (when it arrives) | |")
    L.append("")
    L.append("**The effective registration date is the day the Office receives all three items together.**")
    L.append("")
    L.append("---")
    L.append("© 2026 Erik Daniel Lindquist. Zone P.")
    L.append("")
    return "\n".join(L)


for w in WORKS:
    (HERE / f"{w['slug']}.md").write_text(sheet(w), encoding="utf-8")
    print("wrote", w["slug"] + ".md")
