#!/usr/bin/env python3
"""
Fill Form TX seven times from one definition and merge into a single print file.

Why an overlay rather than AcroForm values: merging seven copies of the same
form collides on field names — every copy would display the same title. So the
values are drawn as static text at the widget rectangles and flattened onto the
page. No form fields survive in the output, which means it prints identically in
any viewer, on any printer.

Blank form: pages 0-1 are instructions, pages 2-3 are the application. Only the
application pages are emitted: 7 x 2 = 14 pages. Print once, separate into
seven, sign seven times.

Deliberately left empty for pen: street address (3 places), telephone, signature
and date. Nothing about the claimant is invented.
"""

import io
import pathlib
from pypdf import PdfReader, PdfWriter
from reportlab.pdfgen import canvas
from reportlab.pdfbase.pdfmetrics import stringWidth

HERE = pathlib.Path(__file__).parent
BLANK = HERE / "formtx.pdf"
OUT = HERE / "FormTX_ALL_SEVEN_to_print.pdf"

FORM_PAGES = (2, 3)          # application pages inside the blank
FONT, SIZE, LEAD = "Helvetica", 8.5, 9.5

AUTHOR = "Erik Daniel Lindquist"
EMAIL = "el.3079@gmail.com"

CONST = {
    "Name of Author": AUTHOR,
    "Citizen of": "United States",
    "Copyright Claimant(s)": AUTHOR,
    "Correspondence": AUTHOR,
    "Email": EMAIL,
    "Printed Name": AUTHOR,
    "Name_3": AUTHOR,
    "Year_2": "2026",                 # 3a, year completed
}
CHECKS = ["Work Made For Hire - No", "Anonymous - No", "Pseudonymous - No",
          "Previous Registration - No", "Author - Yes"]
# Space 3b (Month/Day/Year/Nation) intentionally untouched: empty = unpublished.

WORKS = [
    (1, "The Atlas of Self - Autobiography Log",
        "Text, selection, coordination, and arrangement of literary material.",
        "Text generated by artificial intelligence.",
        "Text, selection, coordination, and arrangement by the author."),
    (2, "Ouroboros",
        "Text (the author's questions), selection, and arrangement.",
        "Answer summaries and annotations generated by artificial intelligence.",
        "The author's questions; selection and arrangement."),
    (3, "A Framework for Building Her Own Framework",
        "Text.", "", ""),
    (4, "Nursing State - A Traveler's Guide",
        "Selection, coordination, and arrangement; text of the underlying framework.",
        "Text generated by artificial intelligence.",
        "Selection, coordination, and arrangement; text of the underlying framework."),
    (5, "Guided Mastery - A Framework",
        "Text, selection, coordination, and arrangement.",
        "Text generated by artificial intelligence.",
        "The framework, its sequence and rules, and the selection, coordination, "
        "and arrangement of the text, by the author."),
    (6, "Course Mastery Coach - A Framework",
        "Text, selection, coordination, and arrangement.",
        "Text generated by artificial intelligence.",
        "The framework, its sequence and rules, and the selection, coordination, "
        "and arrangement of the text, by the author."),
    (7, "Guided Mastery - A Case Study",
        "Text, selection, coordination, and arrangement.",
        "Text generated by artificial intelligence.",
        "The case, its analysis and results, and the selection, coordination, "
        "and arrangement of the text, by the author."),
]


def field_boxes():
    """{page_index: {field_name: (x0, y0, x1, y1)}} for the application pages."""
    reader = PdfReader(str(BLANK))
    out = {p: {} for p in FORM_PAGES}

    def name(o):
        parts, cur, n = [], o, 0
        while cur is not None and n < 6:
            t = cur.get("/T")
            if t:
                parts.append(str(t))
            cur = cur.get("/Parent")
            if cur is not None:
                cur = cur.get_object()
            n += 1
        return ".".join(reversed(parts))

    for pi in FORM_PAGES:
        for a in reader.pages[pi].get("/Annots") or []:
            o = a.get_object()
            if o.get("/Subtype") != "/Widget":
                continue
            r = [float(v) for v in o.get("/Rect")]
            out[pi][name(o)] = (min(r[0], r[2]), min(r[1], r[3]),
                                max(r[0], r[2]), max(r[1], r[3]))
    return out


def wrap(text, width):
    words, lines, cur = text.split(), [], ""
    for w in words:
        trial = (cur + " " + w).strip()
        if stringWidth(trial, FONT, SIZE) <= width:
            cur = trial
        else:
            if cur:
                lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines


def overlay(values, checks, boxes, pi, size):
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=size)
    # set colours explicitly: merged content otherwise inherits whatever graphics
    # state the base page left behind, which silently swallowed the checkmarks
    c.setFillColorRGB(0, 0, 0)
    c.setStrokeColorRGB(0, 0, 0)
    c.setFont(FONT, SIZE)
    for fname, text in values.items():
        box = boxes[pi].get(fname)
        if not box or not text:
            continue
        x0, y0, x1, y1 = box
        avail = (x1 - x0) - 4
        lines = wrap(str(text), avail)
        # start high in the box so multi-line text grows downward inside it
        y = y1 - SIZE - 1 if len(lines) > 1 else y0 + (y1 - y0 - SIZE) / 2 + 1.5
        for ln in lines:
            c.drawString(x0 + 2, y, ln)
            y -= LEAD
    # Checkmarks are FILLED blocks, not strokes. The blank form leaves a graphics
    # state that swallows stroked paths on merge — lines were present in the
    # content stream and rendered as nothing. Fills survive, so the box is filled
    # solid: unambiguous on paper, and it cannot silently disappear.
    for fname in checks:
        box = boxes[pi].get(fname)
        if not box:
            continue
        x0, y0, x1, y1 = box
        i = 0.6
        c.rect(x0 + i, y0 + i, (x1 - x0) - 2 * i, (y1 - y0) - 2 * i,
               stroke=0, fill=1)
    c.save()
    buf.seek(0)
    return PdfReader(buf).pages[0]


def build():
    boxes = field_boxes()
    writer = PdfWriter()
    for n, title, nature, pre, added in WORKS:
        values = dict(CONST)
        values["Title of This Work"] = title
        values["Nature of Authorship"] = nature
        if pre:
            values["Preexisting Material"] = pre
            values["Material Added to This Work"] = added
        reader = PdfReader(str(BLANK))
        for pi in FORM_PAGES:
            page = reader.pages[pi]
            w = float(page.mediabox.width)
            h = float(page.mediabox.height)
            page.merge_page(overlay(values, CHECKS, boxes, pi, (w, h)))
            # Drop the widget annotations. They render ON TOP of page content,
            # so the blank checkboxes' "off" appearance was painting over the
            # marks. Removing them also kills the duplicate-field-name collision
            # that merging seven copies of one form would otherwise cause.
            if "/Annots" in page:
                del page["/Annots"]
            writer.add_page(page)
        print(f"  packet {n}: {title}")
    with open(OUT, "wb") as fh:
        writer.write(fh)
    print(f"\nwrote {OUT.name}  ({len(writer.pages)} pages = 7 applications x 2)")


if __name__ == "__main__":
    build()
