# Armored ServiceNow: Now Assist Skill Kit — Public documentation only.
BOOK=dict(
 title="Armored ServiceNow: Now Assist Skill Kit",
 subtitle="Advanced practice for the people building generative-AI skills and custom apps on the platform",
 platform="ServiceNow",
 sources=[
  ("ServiceNow Product Documentation — Now Assist Skill Kit","docs.servicenow.com › Now Assist › Now Assist Skill Kit (skills, prompts, tools, grounding, testing, deployment)"),
  ("ServiceNow Product Documentation — Generative AI Controller","docs.servicenow.com › Generative AI Controller (providers, capabilities)"),
  ("ServiceNow Product Documentation — App Engine Studio and application scope","docs.servicenow.com › App Engine (scoped applications, delegated development)"),
 ],
 items=[
 dict(concept="What a skill is",stem="A developer says she 'wrote a prompt' and wants it in the Incident workspace. In Skill Kit terms, what is missing before it can be used?",
  opts=[("Nothing — a prompt is a skill","ABS"),("A skill wraps the prompt with inputs (grounding), an optional tool, an output definition, testing, and a deployment target; the prompt alone is one part","KEY"),("A business rule","CONF"),("An update set","ADJ")],
  target="prompt vs SKILL",deciding="A skill is prompt + data in + action out + where it appears.",rule="Skill = prompt + grounding + tool + output + deployment.",camo=["Incident workspace"]),
 dict(concept="Skill types",stem="Three asks: (1) shorten a long case into a paragraph; (2) write a knowledge article from a resolved incident; (3) answer questions over a set of documents. Which skill patterns?",
  opts=[("1 summarization · 2 generation · 3 Q&A / retrieval-grounded chat","KEY"),("All three are summarization","DROP"),("1 generation · 2 summarization · 3 classification","INV"),("All three require a custom LLM","ABS")],
  target="shorten · write · answer",deciding="The verb picks the pattern.",rule="Summarize compresses; generate creates; Q&A retrieves then answers.",camo=[]),
 dict(concept="Grounding",stem="The summary skill keeps inventing details not on the case. What is the correct fix?",
  opts=[("A longer prompt telling it not to invent","ADJ"),("Ground the skill on the case record's fields and related records (comments, work notes) so the model only sees real data","KEY"),("Switch providers","ADJ"),("Lower the output length","DROP")],
  target="INVENTING details",deciding="Hallucination is a grounding problem before it is a prompt problem.",rule="Grounding = the record data the skill is allowed to see. Unknown resolves to nothing.",camo=[]),
 dict(concept="Tools",stem="A skill must look up the customer's entitlement in another table before answering, and the value must be exact. Which Skill Kit component performs the lookup?",
  opts=[("The prompt, by asking the model to recall it","INV"),("A tool — a script, subflow, or retriever that fetches data deterministically and passes it to the prompt","KEY"),("A UI action","CONF"),("An ACL","CONF")],
  target="must be EXACT",deciding="Deterministic facts come from tools, not from the model.",rule="Tools fetch; the model composes. Server decides, client renders.",camo=[]),
 dict(concept="Generative AI Controller and providers",stem="Security asks where the prompt goes. The skill uses 'Now LLM' — what does that mean, and what is the alternative path?",
  opts=[("The prompt is sent to ServiceNow-hosted models via the Generative AI Controller; the alternative is a configured third-party provider (e.g., through a connector), which is a separate data path and approval","KEY"),("The prompt runs on the instance's own CPU","INV"),("The prompt goes to whichever model is cheapest","ABS"),("There is no way to know","ABS")],
  target="WHERE the prompt goes",deciding="The controller is the switchboard; provider choice is a data-path decision.",rule="Know the provider before the prompt leaves.",camo=[]),
 dict(concept="Testing a skill",stem="Before publishing, the developer wants to run the skill against ten real-looking records and compare outputs. Where?",
  opts=[("In Skill Kit's test/evaluation area — run against sample records, review outputs, iterate on prompt and grounding","KEY"),("In production on live cases","INV"),("In a spreadsheet","ADJ"),("Testing is not possible for generative skills","ABS")],
  target="BEFORE publishing",deciding="Skill Kit includes testing; publishing is a separate step.",rule="Test → publish → deploy, in that order.",camo=[]),
 dict(concept="Publishing and deployment",stem="The skill tests well. Users still do not see it on the incident record. What are the remaining steps?",
  opts=[("Publish the skill, then deploy it to a capability/UI surface (e.g., a workspace panel or UI action) and enable it in Now Assist admin","KEY"),("Restart the instance","INV"),("Add the user to admin","ABS"),("Nothing — publishing deploys everywhere","ABS")],
  target="tests well · not visible",deciding="Publish makes it available; deploy places it.",rule="Publish ≠ deploy ≠ enable.",camo=[]),
 dict(concept="Roles and delegated development",stem="A business analyst wants to build skills but must not modify ACLs or global scripts. How is this arranged?",
  opts=[("Skill Kit roles for building skills plus delegated development permissions inside a scoped application; no admin","KEY"),("Grant admin temporarily","ABS"),("Have IT build everything","ADJ"),("Use the global scope","INV")],
  target="build skills · NOT touch ACLs",deciding="Scoped app + delegated development bounds what a builder can change.",rule="Citizen development is safe when the scope is the fence.",camo=[]),
 dict(concept="Application scope",stem="A custom app built in App Engine Studio needs to read incidents and write to its own tables. A developer gets an error writing to incident. Why?",
  opts=[("Cross-scope access is governed; a scoped app can be granted read but writing to another scope's table requires explicit cross-scope privilege","KEY"),("Incident is read-only for everyone","ABS"),("The app needs the admin role","ADJ"),("The app must be moved to global","INV")],
  target="its own tables vs ANOTHER scope",deciding="Scope is a boundary with explicit doors.",rule="Scoped apps own their tables; cross-scope access is declared.",camo=[]),
 dict(concept="Output definition",stem="A generation skill should return a title, a body, and a confidence note, and the UI should place each in its own field. What makes that possible?",
  opts=[("A structured output definition on the skill (schema) that the deployment maps to fields","KEY"),("Asking the model to use headings","ADJ"),("Three separate skills","DROP"),("A business rule that parses text","INV")],
  target="each in its OWN field",deciding="Structured output is defined, not parsed.",rule="Define outputs; map them.",camo=[]),
 dict(concept="Sensitive data",stem="Cases sometimes contain card numbers in comments. The skill summarizes comments. What must the design address?",
  opts=[("Data privacy controls — masking/exclusion of sensitive fields and content before grounding, per the platform's sensitive data handling","KEY"),("Nothing; the model forgets","ABS"),("Use a third-party provider","INV"),("Turn off comments","DROP")],
  target="card numbers in COMMENTS",deciding="What is grounded is what is sent.",rule="Mask or exclude before grounding; the red line is upstream of the prompt.",camo=[]),
 dict(concept="Skill vs AI agent",stem="A stakeholder wants 'AI that fixes the incident.' The developer has built a summarization skill. What is the distinction?",
  opts=[("A skill produces content on request; an AI agent (Agent Studio) plans and takes actions through tools with human oversight — different construct, different governance","KEY"),("They are the same feature","ABS"),("A skill can take any action if the prompt says so","INV"),("Agents replace skills","ABS")],
  target="produce vs ACT",deciding="Content vs action is the line.",rule="Skill = output. Agent = actions. Governance scales with action.",camo=[]),
 dict(concept="Prompt design in Skill Kit",stem="The prompt says: 'Summarize this incident.' Outputs vary wildly in length and tone. What is the most reliable improvement?",
  opts=[("Specify structure, length, audience and what to exclude, and supply the grounded fields by name","KEY"),("Add 'please'","DROP"),("Run it twice","ADJ"),("Raise temperature","INV")],
  target="VARY wildly",deciding="Unspecified = variable.",rule="Say the shape; ground the facts.",camo=[]),
 dict(concept="Usage and monitoring",stem="After launch, the owner wants to know how often the skill is used, accepted, edited or rejected. Where does that live?",
  opts=[("Now Assist usage/analytics — adoption and feedback metrics per skill","KEY"),("The incident table","ADJ"),("The system log only","DROP"),("It is not tracked","ABS")],
  target="used · accepted · edited",deciding="Skills carry telemetry.",rule="Every human decision on a skill output is a label.",camo=[]),
 dict(concept="Retriever-grounded Q&A",stem="A Q&A skill must answer from the approved knowledge base only, never from the model's general knowledge. What is required?",
  opts=[("A retriever tool over the knowledge base as grounding, with the prompt constrained to the retrieved passages","KEY"),("A bigger model","INV"),("A prompt that says 'only use our KB'","ADJ"),("Copying the KB into the prompt","DROP")],
  target="approved KB ONLY",deciding="Retrieval bounds the answer space.",rule="Retrieve → constrain → answer with citations.",camo=[]),
 dict(concept="Versioning and change",stem="A prompt change breaks a working skill in production. What should have happened?",
  opts=[("Iterate and test a new version in sub-production, capture in an update set/app version, and promote — the skill is configuration like any other","KEY"),("Edit in production; it is only text","INV"),("Skills cannot be versioned","ABS"),("Ask the vendor","ADJ")],
  target="BROKE in production",deciding="A skill is configuration.",rule="Skills follow the same transport discipline as everything else.",camo=[]),
 ])
