# Joshua Says · The Traveler's Guide — public edition (V1). De-identified: written to "you", not to a named person.
BOOK=dict(
 title="The Traveler's Guide: Nursing State and Owner's County",
 subtitle="A framework you build yourself — financial literacy, your own salon by your house, getting around without owning the car, and the road into nursing",
 platform="",
 disclaimer=("Information, not advice. Nothing here is financial, legal, medical or career advice; every number is an illustration with its assumptions stated, and the real figures live at your college's financial-aid office, your state licensing board, your lender and your accountant. "
             "Tesla and Robotaxi are trademarks of their owner; this book is independent and unaffiliated. Written by the author from the author's own method; no individual is named."),
 intro=[["1","<b>This is not a plan to follow.</b> It is a way to build your own, so it is yours and it still works on the days nothing goes right."],
        ["2","<b>Read it once through, then throw the plan away and keep the five questions</b> at the end. A plan breaks the first month it meets your actual life. The questions do not."],
        ["3","<b>Every number is an illustration.</b> The assumptions are printed beside it. Change the assumption and the number changes; that is the point."],
        ["4","<b>One small thing before your next haircut.</b> Each chapter ends with one. That is the whole assignment."]],
 sources=[("Your nearest community college — nursing page and financial-aid office","One search, one phone number, one call. The real costs and the real help live there"),
          ("Your state's board of nursing","Licensing ladder: certificate → practical → registered → bachelor's"),
          ("Your state's cosmetology board and your city's business licensing office","What owning a chair, then a shop, actually requires where you live"),
          ("The ride service's published pricing where you live","Per-ride cost against the cost of owning a second car — check it the week you decide")],
 sections=[
  dict(h="A word before you go",p=[
   "Every guide begins with a confession from whoever wrote it, so here is mine: I have watched people decide that the only trip they get to take is the one where they drive their children to the trailhead, wave, and watch them walk in without them. Put that map down. It is the wrong one. This guide is for a different trip — yours.",
   "I will not sell you a fantasy. Nursing State is a real place, and real places have distance, weather, and a cost of entry. I am going to tell you it is walkable — that there is a marked road, that people who look a great deal like you make this drive every year, and that the first steps are small enough to take before this week is out. Honest beats hopeful. Here, the honest thing is also the hopeful one."]),
  dict(h="Your traveler's résumé — you are more ready than you think",p=[
   "If you run a chair, you run a business. A stylist's chair is a book of loyal clients, a pricing strategy, a calendar you defend, and a reputation built one good haircut at a time — that is small-business operation, done under someone else's sign. Steady hands and a gift for putting nervous strangers at ease for hours are, in a hospital, half the job.",
   "Here is what a travel agent reads in that: you do hard things, on a schedule, for the people you love, without quitting. That is the entire spec sheet for this trip. The confidence you swear you do not have, you have been spending every day. You have just never billed it to your own account."]),
  dict(h="Five things are already running",p=[
   [["System","What it is","What it needs from you"],
    ["The chair","Your income. Steady, skilled, portable","Protect it. It pays for everything else"],
    ["Your family","Not something to work around — the wall everything else is built on","Bring them in on purpose; logistics are the thing you are already best at"],
    ["Nursing","Long road, big payoff. It raises the ceiling on everything else","One step every two weeks"],
    ["The salon","Owning instead of renting your hours. Real risk, real upside","Knowledge banked before money spent"],
    ["What you keep","The part that outlasts all of it — the trip fund, the cushion, the habit","An automatic transfer, any amount, from day one"]],
   "Two of these are quietly fighting. Nursing and the salon want the same hour, and you do not have two of that hour. One goes first and pays for the other. The chapters below are in that order."]),
  dict(h="Financial literacy — the ladder, not the bet",p=[
   "A bet multiplies risk. Security multiplies time. Those are opposite instruments, and a hundred dollars is the wrong unit for either. It is the one table where the house, over time, always keeps the hundred. The table below is the other kind — the rare one where a little, set down again and again, does not vanish. Same hope. Better table.",
   [["What you put in","10 years at 4%","20 years at 4%","20 years at 7% (historical average, not guaranteed)"],
    ["$100 once","$149","$222","$405"],
    ["$14 every two weeks","$4,500","$11,100","$15,800"],
    ["$25 every two weeks","$8,000","$19,900","$28,300"],
    ["$50 every two weeks","$16,000","$39,800","$56,600"]],
   "Three things the table says. The first five years are almost all contribution — the rate barely matters; the habit is the whole return. The rate starts to matter around year ten. And year one at any amount above the smallest covers a nursing prerequisite class, which is how this rung funds the next.",
   "Your ladder, in order: the chair (costs nothing, already paying) → the automatic transfer (any amount; stop it any time) → nursing (the application fee, then tuition; the licence cannot be taken back) → the salon (lease, licence, build-out — the only rung that eats capital, so it comes last and is paid for by the rungs above it).",
   "Every two weeks, three numbers said out loud: Did the cycle cover itself, and did something go aside automatically? One step toward nursing? One thing learned about owning? If the first is red, nothing else matters this cycle. That is not failing. That is the system telling you where the one spare hour goes.",
   "One small thing: set up an automatic transfer this week. Any amount. Pick the day right after you are usually paid so you never have to decide again."]),
  dict(h="Owner's County — your own G.O.A.T. salon, by your house",p=[
   "The layover is where this stops feeling like a leap and starts feeling like a life. Owner's County is your own town — no hour there, no hour back. The chair is yours, the sign over the door is your name, and you did not just move the chair closer to home; you moved the whole business under your own roof.",
   "Here is the quiet thing that happens on the way in: you become fluent in money. Not from a class — from running a shop, which teaches the language whether you mean to learn it or not. You read your own numbers. You know what a good week looks like on paper, and why. You price your work like someone who can see the math. You keep a cushion, so a slow month is weather and not a wall. You pay yourself first, on purpose, every time — and it stops feeling selfish the day you understand it is the very thing that keeps the doors open.",
   [["Before you spend a dollar, bank these","Where"],
    ["How booth rental actually works where you live — what the chair pays, what it keeps","One conversation with someone who owns a salon"],
    ["What the lease, the licence and the build-out cost, in your town, this year","Your city's licensing office; one landlord; one contractor"],
    ["What a good week and a bad week look like on paper, from a real book","Your own book, kept for three months, honestly"],
    ["The one number that says go: months of cushion the shop needs before it pays you","Your own arithmetic, from the row above"]],
   "Because you budget on purpose now, there is a line in it with a name — the trip fund — and the shop feeds it. Not whatever is left over; a real line, paid first. The family travel you filed under someday has a number and a date on it, and none of it rides on a card.",
   "One small thing: have one conversation with someone who owns a salon. Not to ask for anything. To learn one thing you do not know yet."]),
  dict(h="Getting around without owning the car — the Robotaxi question",p=[
   "Two hours in a car each day are not lost time, but they are the longest uninterrupted stretch you get, and a car you own costs you whether it moves or not. The honest question for a traveler on this road is not whether to ride but what a ride costs against what the car costs.",
   [["Ownership cost (illustration — put your own numbers in)","Monthly"],
    ["Payment or the money tied up in the car","$350–$550"],
    ["Insurance","$120–$200"],
    ["Fuel or charging","$100–$200"],
    ["Maintenance, tires, registration, averaged","$80–$150"],
    ["Total","$650–$1,100"]],
   "Against that, a per-ride service — an autonomous one where it operates, or an ordinary one where it does not — is a number you can look up the week you decide, multiplied by the rides you actually take: clinicals, class, the salon, the school run. If the rides total less than the car, the difference goes to the transfer in the financial chapter. If they total more, the car stays and this chapter cost you one afternoon of arithmetic.",
   "What this chapter does not know: where autonomous service operates this year, and at what price. Check it where you live; the answer changes by city and by season. What it does know: the commute is a study hall — a recorded lecture, an audiobook, a set of cards — and a ride you do not drive turns two dead hours into two working ones.",
   "One small thing: add up one week of the rides you would actually take, at the published price, and write the number next to the car's monthly cost."]),
  dict(h="Nursing State — the map, the itinerary, the budget",p=[
   "The highway into Nursing State has numbered exits, and this is the part most people miss: you do not drive the whole way in one leg. It is a ladder, and every rung is a real place you can stand, work, and get paid while you climb to the next.",
   [["Rung","What it is","How long","What it does"],
    ["The on-ramp","A short certificate","Weeks, not years","You are working in the building, earning, seeing the job up close"],
    ["The next town","A licensed practical role","About a year","More responsibility, more pay"],
    ["The city","The registered nurse, through a community college","About two years","The destination most people mean when they say nurse"],
    ["And beyond","The bachelor's and further","If and when you want it","The ceiling raised again"]],
   "The itinerary — what you do this week, and nothing more. Find the nearest community college's nursing page: one search, one phone number. Make one call to an advisor — you are not committing; you are asking a stranger for directions, which is exactly what travelers do: If I wanted to start around my job and my kids, what is my first step and what does it cost? In the same call, ask about money: What help is there for a working parent? There is more than you think.",
   "The budget. The community-college on-ramp is the affordable road on purpose — it exists so people without a pile of savings can begin. The money that helps you travel is aimed almost precisely at you: help for parents, for people in rural places, and for anyone heading into healthcare, where the country is short on nurses and quietly desperate to pay people to become them. I will not quote numbers I would have to invent; the real ones live at the financial-aid office, and getting them is one more phone call, not a leap.",
   "Storms and detours. When a test comes back wrong or a month falls apart: slow down, do not turn around, keep the people you love on the far side of the storm fixed in your mind. Detours add miles. They do not cancel the trip.",
   "One small thing: one search, one phone number, one call."]),
  dict(h="Now throw mine away — the five questions",p=[
   "Anyone can hand you a plan. A plan breaks the first month it meets your actual life. These five do not, because you answer them yourself, and you can answer them again whenever things change.",
   [["","The question"],
    ["One","What pays for everything else — and am I protecting it?"],
    ["Two","Which two of my dreams are secretly fighting over the same hour, and which one should pay for the other?"],
    ["Three","What runs quietly in the background from day one, whether or not I am thinking about it?"],
    ["Four","What can I answer every two weeks about where my one spare hour went?"],
    ["Five","What am I assuming that, if it turned out wrong, would change the order of everything — and have I said it out loud to someone?"]],
   "Two things this book does not know. It assumes the chair holds; if it wobbles, the order changes — the order is meant to be rearranged; the five questions are not. And it assumes nursing before the salon; if a real salon chance appears and will not wait, take it and re-order. Do not let a plan outrank your own judgment about your own life.",
   "The stamp. Every place in this atlas earns a stamp when you arrive, and here is the secret of the first one: you do not earn it by finishing. You earn it by starting — by making the call, by standing on the first rung. That is the border of Nursing State, and you can cross it this week.",
   "There is no version of raising your children to this road more powerful than letting them watch you walk it."]),
 ],
 items=[],
)
