# Armored ServiceNow CSM (the CRM module) — Public documentation only.
BOOK=dict(
 title="Armored ServiceNow: Customer Service Management",
 subtitle="Advanced practice for agents, admins and service owners on the CRM side of the platform",
 platform="ServiceNow",
 sources=[
  ("ServiceNow Product Documentation — Customer Service Management","docs.servicenow.com › CSM (cases, accounts, contacts, entitlements, Agent Workspace, playbooks, Advanced Work Assignment)"),
  ("ServiceNow Product Documentation — Customer Service Portal and Communities","docs.servicenow.com › Service Portal / Communities"),
  ("ServiceNow University — CIS-CSM mainline blueprint","learning.servicenow.com (public exam outline; no exam item reproduced)"),
 ],
 items=[
 dict(concept="Case vs incident",stem="An external customer emails that her subscription renewed at the wrong price. An internal employee reports his laptop will not boot. Same instance, same day. Which tables?",
  opts=[("Both incidents","DROP"),("The customer's issue is a Case (CSM); the employee's is an Incident (ITSM)","KEY"),("Both cases","DROP"),("A case for the employee, an incident for the customer","INV")],
  target="EXTERNAL customer vs INTERNAL employee",deciding="CSM serves customers; ITSM serves the workforce.",rule="Case = external customer issue. Incident = internal service disruption.",camo=["same instance, same day"]),
 dict(concept="Account, contact, consumer",stem="A B2B customer's IT director opens a case; separately, an individual who bought one device at retail opens one. How is each person modelled?",
  opts=[("Both as Contacts","DROP"),("The director is a Contact under an Account; the retail buyer is a Consumer","KEY"),("Both as Consumers","DROP"),("The director is an Account","ADJ")],
  target="B2B person vs B2C person",deciding="Contact belongs to an account; consumer stands alone.",rule="Account (company) → Contacts (people). Consumer = individual customer with no account.",camo=["one device at retail"]),
 dict(concept="Entitlements",stem="A customer demands 24×7 phone support. Their contract covers business-hours email support only. Where should the agent be able to see that, and what enforces it?",
  opts=[("Entitlements linked to the account/contract, checked on the case and used to drive SLA and channel","KEY"),("The account's notes field","DROP"),("The SLA definition alone","ADJ"),("The customer portal FAQ","CONF")],
  target="what they are ENTITLED to",deciding="Entitlement records tie contract terms to service.",rule="Contract → entitlement → case eligibility and SLA.",camo=["24×7"]),
 dict(concept="Case SLAs",stem="Premium accounts get a 2-hour first response; standard get 8. One SLA definition exists with an 8-hour duration. What is the right design?",
  opts=[("Edit the duration to 2 for everyone","DROP"),("Two SLA definitions with conditions on the account's service level (or entitlement), each with its own duration and schedule","KEY"),("A business rule that changes priority","ADJ"),("An assignment rule","CONF")],
  target="different terms by ACCOUNT",deciding="Conditions select which SLA attaches.",rule="One definition per commitment; conditions decide which case gets which.",camo=[]),
 dict(concept="Advanced Work Assignment",stem="Chat cases should go to the agent with the fewest open chats who has the 'Billing' skill and is available. Which capability, and what is configured?",
  opts=[("Advanced Work Assignment — queues, skills, agent capacity and availability, with an assignment rule pushing work to agents in a workspace inbox","KEY"),("An assignment rule on the case table","ADJ"),("Round-robin by group","ADJ"),("On-call scheduling","CONF")],
  target="fewest open · has the skill · available",deciding="Push assignment with capacity and skills is AWA.",rule="AWA routes work items to agents; assignment rules route records to groups.",camo=[]),
 dict(concept="Agent Workspace",stem="Agents complain about tab-switching between the case, the customer's history, knowledge, and chat. Which UI is designed for that, and what is it built from?",
  opts=[("Agent Workspace (configurable workspace) — lists, record pages, ribbon components, contextual side panel, built in UI Builder","KEY"),("The classic form with related lists","ADJ"),("Service Portal","CONF"),("A dashboard","ADJ")],
  target="one screen, in context",deciding="Workspace is the agent UI; portal is the customer UI.",rule="Agent Workspace for fulfillers; Service Portal for customers.",camo=[]),
 dict(concept="Playbooks",stem="A refund case must follow six ordered steps with hand-offs between billing and support, and the agent should see progress as a timeline. Which construct?",
  opts=[("A playbook (Process Automation Designer) rendered in the workspace","KEY"),("A knowledge article with a checklist","ADJ"),("Case tasks created manually","DROP"),("A UI policy","CONF")],
  target="ordered steps · timeline",deciding="Playbooks orchestrate stages and activities visually.",rule="Playbook = process stages shown to the agent; tasks alone are not a process.",camo=[]),
 dict(concept="Case types and record producers",stem="On the portal, 'Report a billing problem' and 'Ask a product question' should open cases with different fields and different routing. How?",
  opts=[("Two record producers writing to the case table with different variables and defaults (case type/category), feeding different assignment","KEY"),("Two case tables","INV"),("One record producer and a dropdown","DROP"),("Two knowledge bases","CONF")],
  target="different fields · different routing",deciding="Record producers shape intake; the case table stays one.",rule="Record producers vary the front door, not the table.",camo=[]),
 dict(concept="Major issue management",stem="A software defect affects 400 customers; each is opening a case. Support wants one place to fix and communicate, and every customer case updated when it is resolved. Which capability?",
  opts=[("Major issue management — a parent major case with child cases (and optional proactive cases), resolution propagated to children","KEY"),("A problem record","ADJ"),("A knowledge article","DROP"),("An order guide","CONF")],
  target="400 customers · one fix",deciding="Parent/child cases with propagation.",rule="Major case = one root, many children, one communication.",camo=[]),
 dict(concept="Proactive customer service",stem="A monitored device fleet reports a fault before customers notice. Support wants cases opened automatically for the affected install base. What must exist?",
  opts=[("Install base records (sold products/installed assets) linked to accounts, so an event can create proactive cases against them","KEY"),("A consumer record for each device","ADJ"),("A knowledge base","CONF"),("An SLA","CONF")],
  target="BEFORE customers notice",deciding="Proactive service needs the install base to know who has what.",rule="Install base → affected customers → proactive cases.",camo=[]),
 dict(concept="Case escalation",stem="A customer asks to 'escalate' a case that is within SLA and correctly assigned. What does escalation mean on the platform?",
  opts=[("Automatically raising priority to 1","INV"),("A managed escalation request — a record with reason, approver and tracking, distinct from priority and SLA","KEY"),("Reassigning to a manager","ADJ"),("Nothing; escalation is informal","ABS")],
  target="escalate ≠ priority",deciding="Escalation is its own object with its own workflow.",rule="Priority is impact; escalation is attention.",camo=["within SLA"]),
 dict(concept="Knowledge and case deflection",stem="Portal search shows articles as the customer types a case description; the case volume for password resets drops 30%. Which mechanism is at work?",
  opts=[("Knowledge deflection from the record producer / portal search, with deflection tracked on the knowledge feedback","KEY"),("Virtual Agent","ADJ"),("An SLA","CONF"),("A playbook","CONF")],
  target="as the customer TYPES",deciding="Contextual search on the intake form is deflection.",rule="Deflection = answer before the case exists; measure it.",camo=["30%"]),
 dict(concept="Communities",stem="Customers want to answer each other's questions and have accepted answers become searchable. Which capability?",
  opts=[("Communities — forums, questions, accepted answers, optionally harvested into knowledge","KEY"),("Case comments","DROP"),("Live chat","ADJ"),("Service catalog","CONF")],
  target="answer EACH OTHER",deciding="Peer support is Communities.",rule="Communities = customer-to-customer; cases = customer-to-agent.",camo=[]),
 dict(concept="Omni-channel",stem="Phone (via CTI), chat, email and a web form all create cases. Agents should see channel and be routed by channel capacity. What ties this together?",
  opts=[("Channel-aware intake (CTI/OpenFrame, chat via AWA, inbound email actions, record producers) into one case table, with AWA capacity per channel","KEY"),("A separate table per channel","INV"),("Email only","DROP"),("A dashboard","CONF")],
  target="one table · channel capacity",deciding="Channels differ at intake; the case is one.",rule="Many doors, one room.",camo=[]),
 dict(concept="Special handling notes",stem="A VIP account has an instruction: 'Never call after 6 pm; always cc the account manager.' Agents keep missing it in the account notes. Which feature surfaces it?",
  opts=[("Special handling notes — displayed prominently on the case/account in the workspace","KEY"),("A knowledge article","ADJ"),("A UI policy","CONF"),("An entitlement","ADJ")],
  target="agents keep MISSING it",deciding="Special handling notes are designed to be seen.",rule="Instruction that must be seen → special handling note.",camo=[]),
 dict(concept="Outsourced customer service",stem="A partner company handles tier-1 support for one product line and must see only those accounts' cases. Which model?",
  opts=[("Partner/outsourced service — partner accounts and contacts with restricted access to the cases they serve","KEY"),("Give partner staff the admin role","ABS"),("A separate instance","INV"),("A community","CONF")],
  target="see ONLY those accounts",deciding="Partners are modelled, and access is scoped.",rule="Partner relationship + access scoping, not roles alone.",camo=[]),
 dict(concept="Satisfaction surveys",stem="After case closure, a survey should go out, and the score should be reportable by agent and account. Which capability?",
  opts=[("Survey/assessment triggered on case closure with results reportable","KEY"),("A closure note","DROP"),("A knowledge feedback","ADJ"),("An SLA","CONF")],
  target="after closure · reportable",deciding="Surveys are triggered assessments.",rule="Trigger on state; report on the assessment table.",camo=[]),
 dict(concept="Case action status and state",stem="A case is In Progress but the ball is with the customer. Agents want the list to show that at a glance without changing the state. Which field?",
  opts=[("Action status (e.g., Awaiting info) alongside State","KEY"),("Priority","CONF"),("Escalation","ADJ"),("Assignment group","DROP")],
  target="without changing the STATE",deciding="Action status is orthogonal to state.",rule="State = lifecycle; action status = who has the ball.",camo=[]),
 dict(concept="Customer Service Portal",stem="Customers need to open cases, see their own cases only, read knowledge, and chat. Which delivery, and what governs 'their own cases only'?",
  opts=[("The Customer Service Portal (Service Portal) with ACLs/queries restricting cases to the contact's account","KEY"),("Agent Workspace with limited roles","ADJ"),("Email only","DROP"),("Communities","CONF")],
  target="their OWN cases only",deciding="Portal for customers; access rules enforce scope.",rule="Portal = channel. ACL = scope.",camo=[]),
 dict(concept="Service organization vs account hierarchy",stem="A global customer has regional subsidiaries; cases should roll up to the parent for reporting while each region keeps its contacts. How is this modelled?",
  opts=[("Account hierarchy — parent/child accounts, with contacts on the child accounts and reporting rolled up","KEY"),("One account with all contacts","DROP"),("Consumers for each region","INV"),("Separate instances","INV")],
  target="ROLL UP · keep contacts local",deciding="Hierarchy gives both.",rule="Parent account contains child accounts; contacts live where they work.",camo=[]),
 ])
