# Joshua Says · Armored Integration — Public APIs only. Whisper coaching · warm transfer · hot transfer · intelligent IVR deflection.
BOOK=dict(
 title="Armored Integration: Whisper, Warm, Hot",
 subtitle="Real-time whisper coaching, warm transfer to coaches, hot transfer to leadership, and a truly intelligent IVR at the top of the funnel — across Genesys Cloud CX and ServiceNow ITSM/CSM, on their public APIs",
 platform="ServiceNow and Genesys",
 sources=[
  ("Genesys Cloud Developer Center — Platform API","developer.genesys.cloud › Conversations API (monitor / coach / barge, consult and blind transfer), Notifications API (WebSocket topics), Speech and Text Analytics API, Routing and Users APIs"),
  ("Genesys Cloud Resource Center — Architect and integrations","help.mypurecloud.com › Architect data actions, web services data actions integration, Agent Assist / Agent Copilot, supervisor coaching"),
  ("ServiceNow Developer Documentation — REST APIs","developer.servicenow.com › Table API, Scripted REST APIs, Import Set API, Advanced Work Assignment, Now Assist / Generative AI APIs, Computer Telephony Integration (OpenFrame)"),
  ("Google Cloud — Contact Center AI Platform documentation","cloud.google.com/contact-center (reference frame only)"),
 ],
 sections=[
  dict(h="The design in one page",p=[
   "Three moments, one loop. The floor hears the call; the machine sequences who should hear it next; the human decides. Nothing in this design lets a machine evaluate a person — it only routes attention.",
   [["Moment","What happens","Who acts","Where it runs"],
    ["Whisper","A coach hears the live call and speaks to the agent only; the customer hears nothing","Coach, invited by a signal","Genesys Cloud — supervisor coaching on the conversation"],
    ["Warm","The agent consults a coach on the line, introduces the customer, then drops or stays","Agent, with the coach","Genesys Cloud — consult transfer"],
    ["Hot","The call goes straight to leadership with context attached; no consult","Agent or the rule","Genesys Cloud — blind transfer, with the ServiceNow record on the pop"],
    ["Deflect","The caller is served or routed before a queue is ever touched — by data, not by a chatbot","The IVR, on ServiceNow data","Architect inbound flow + data actions to ServiceNow"]],
   "The signal that invites a whisper is the interesting part. Sentiment and topic detection from Speech and Text Analytics, plus case state from ServiceNow, produce a score. The score sequences which calls a coach hears. It never grades the agent — that contract is written first, so nobody fights it."]),
  dict(h="Whisper coaching — the API surface",p=[
   "1. Subscribe. Open a Notifications channel and subscribe to the queue's conversation topics so the coaching service sees calls as they connect and change state (Notifications API: create channel → WebSocket → subscribe to conversation topics for the queue or users).",
   "2. Score. For each live call, poll or stream Speech and Text Analytics for sentiment trend and detected topics; join with the ServiceNow case or incident (Table API on the record the screen-pop opened) for state, priority, entitlement and escalation flags. Publish a whisper score.",
   "3. Invite. When the score crosses the threshold, notify the on-shift coach (Genesys presence and routing status decide who is free) with one action: Listen. The coach joins in monitor mode, then coach mode (Conversations API participant actions: monitor → coach; barge stays reserved for leadership).",
   "4. Record. Write the whisper event — who, when, why, outcome — back to the ServiceNow record as a work note and to the data lake as a label. Every whisper is a training example for the next threshold.",
   "Guardrails: coaching audio is agent-only by platform design; the customer never hears it. Scores are non-determinative — never admissible in performance review. Access to monitor/coach is a Genesys permission scoped by division."]),
  dict(h="Warm transfer to a coach · hot transfer to leadership",p=[
   [["Transfer","Genesys mechanism","ServiceNow side","When the rule fires it"],
    ["Warm","Consult transfer — agent initiates consult to the coach's user or a coaching queue; introduces; completes or cancels","Case/incident stays open; consult logged as a work note; ownership unchanged until the coach accepts","Never automatically. Warm is a human choice; the whisper can suggest it"],
    ["Hot","Blind transfer to a leadership queue with priority routing; the interaction carries the ServiceNow record number as an attribute","Screen-pop of the record via the integration; escalation record created on transfer; leadership sees the whisper score history","On explicit triggers only: threat, legal, regulatory, or the agent's hot key"]],
   "The attribute is the whole trick: set the ServiceNow record number and the whisper score as conversation attributes before transfer (Conversations API attributes), so the receiving pop opens the right record with the right context. Without that, a hot transfer is a cold one with a longer hold."]),
  dict(h="Deflection at the top of the funnel — the intelligent IVR",p=[
   "Not a bot. An IVR is intelligent when it already knows the answer before it asks a question. The intelligence is in the data actions, not in a persona.",
   [["Caller state (from ServiceNow, by ANI or account lookup)","What the IVR does","API"],
    ["Has an open case in Awaiting Customer","Reads the pending question aloud; captures the answer to the case; no queue","Table API read → Architect data action; write back via Table API or Scripted REST"],
    ["Affected by an open major issue / major incident","Proactive announcement with ETA and the option for a callback when resolved; no queue","Table API on major case / major incident; Genesys callback creation"],
    ["Entitlement expired or wrong channel","Routes to the entitled channel or self-service; explains why","Entitlement lookup; Architect decision"],
    ["No record, high-value account","Skips the menu; routes with preferred agent and priority","Account lookup; routing attributes set in flow"],
    ["Nothing known","Short menu, then queue — the only path that touches a human without a reason","Default"]],
   "Measure deflection as cases answered without a queue touch, and re-contacts within seven days. If re-contacts rise, the IVR deflected the wrong thing."]),
  dict(h="Sequence — one call, end to end",p=[
   "Ring → ANI/account lookup (data action → ServiceNow) → IVR decision → queue with attributes → agent pop (record opens) → live scoring (STA + case state) → whisper invite (coach monitors, coaches) → optional consult (warm) → optional hot transfer (leadership queue, attributes carry) → wrap-up and write-back (work note, labels to the lake) → the next threshold learns from the outcome.",
   "Everything above is public API. Nothing requires a custom bot, a new processor, or a vendor engagement. The only incremental cost is compute and the coaches' time — which is the point: it spends their time where the score says it matters."]),
  dict(h="Doing it today, in-house, with the Now Assist Skill Kit — no new platform configuration",p=[
   "Read the constraint literally: nothing changes on the telephony platform, no new integration is built, no vendor is engaged, no new processor or egress is created. The transcripts and sentiment already land on the ServiceNow record through the integration that exists; the case and incident tables already hold the state. Everything below is a skill built in the Now Assist Skill Kit on data that is already there, run by the Generative AI Controller on the in-house model. A skill is configuration inside the boundary; it is not configuration of a platform.",
   [["Skill","Grounding (what it may see)","Tool (deterministic fetch)","Output (structured)","Where it appears"],
    ["Whisper Score","The open case/incident, its work notes, and the attached transcript and sentiment fields from the existing integration","Retriever over related records; a script tool returning entitlement, priority and escalation flags","score 0–100 · one-sentence reason · suggested coach (from the on-shift group)","Agent Workspace side panel for the coach queue; a Flow Designer trigger on record update writes the score to a field"],
    ["Coach Brief","The last N minutes of transcript and the case summary","None beyond grounding","120-word brief: who, what, where it is going, what to listen for","Fires when the score crosses the threshold; delivered by the existing notification to the coach with a link to the record"],
    ["Warm Handoff Note","Case, transcript, the agent's typed intent","None","A three-line introduction the agent reads on consult, plus the work note","UI action on the case — Prepare consult"],
    ["Hot Transfer Context","Case, escalation reason, whisper history","Script tool creating/reading the escalation record","Leadership brief; escalation record fields populated; attributes for the pop","UI action — Escalate to leadership — and the escalation record"],
    ["IVR Answer","The caller's open case in Awaiting Customer, or the major case/incident affecting them","Table read on account/contact match","The pending question as spoken text; the proactive announcement text; the deflection reason code","Returned to the existing Architect data action that already calls ServiceNow — the IVR reads it; no Architect change"]],
   "Order of work, one week, one person with the Skill Kit role in a scoped application: (1) Whisper Score — build, test on twenty closed cases with known outcomes, tune the threshold on the evaluation set, publish, deploy to the coach panel. (2) Coach Brief — build, test, wire to the threshold flow. (3) Warm Handoff Note and Hot Transfer Context — build as UI actions; test the escalation write. (4) IVR Answer — build; return its output through the data action the IVR already calls. (5) Turn on write-back: every skill output and every human accept/edit/reject lands as a label. Promote by update set.",
   "What is deliberately not done: no barge, no automatic hot transfer, no scoring visible to anyone but the coach queue, no third-party model provider, no new data leaving. The eight-months-to-eight-days promise is this list — the platform team's hands stay on the platform; the skill builder's hands stay inside the scope.",
   [["Guardrail","How the Skill Kit enforces it"],
    ["Sensitive content in transcripts","Mask/exclude fields before grounding; the skill never sees what the record does not expose to its role"],
    ["Non-determinative scores","The score is a field with no workflow authority; nothing transitions on it; performance-review reports exclude it by ACL"],
    ["Scope","Skills live in a scoped app with delegated development; cross-scope read on case/incident is declared; no write to platform tables outside the app"],
    ["Provider","Now LLM through the Generative AI Controller; the third-party path is not configured"],
    ["Verification","Skill Kit evaluation set: twenty known cases per skill before publish; human accept/edit/reject tracked after"]],
  ]),
 ],
 items=[
 dict(concept="Skill Kit, not a new integration",stem="An architect proposes a new middleware service to compute the whisper score from Genesys and ServiceNow. The transcripts and sentiment already land on the record. What is the in-house path with no new platform configuration?",
  opts=[("A Whisper Score skill in the Now Assist Skill Kit, grounded on the record and its attached transcript/sentiment, with a script tool for flags, deployed to the coach panel","KEY"),("The middleware, since it is 'real-time'","INV"),("A third-party AI provider","INV"),("A manual spreadsheet","DROP")],
  target="ALREADY land on the record",deciding="If the data is already inside, the skill is the shortest path.",rule="Skill on existing data beats a new pipe.",camo=["'real-time'"]),
 dict(concept="What a skill may not do",stem="Someone wants the Whisper Score skill to also set the case to Escalated when the score is high. Why is that the wrong design?",
  opts=[("Scores sequence attention; a skill output must carry no workflow authority — transitions stay with humans or explicit rules","KEY"),("Skills cannot write fields","ABS"),("Escalation is a Genesys function","CONF"),("It would be too slow","DROP")],
  target="ALSO set the case",deciding="Output ≠ authority.",rule="A skill informs; it does not decide.",camo=[]),
 dict(concept="IVR Answer without touching Architect",stem="The IVR already calls a ServiceNow data action for account lookup. How does the IVR Answer skill reach the caller with no Architect change?",
  opts=[("Its structured output is returned through the same data action response the IVR already reads","KEY"),("A new bot flow","INV"),("A new data action","ADJ"),("An email to the caller","DROP")],
  target="NO Architect change",deciding="Ride the call that exists.",rule="New content, same door.",camo=[]),
 dict(concept="Evaluation before publish",stem="A skill 'looks good' on three cases. What does the Skill Kit expect before it is published to coaches?",
  opts=[("An evaluation set of known cases with expected outputs — here twenty — and a threshold tuned on it; then publish, then deploy","KEY"),("Publish and watch","INV"),("A vendor review","CONF"),("Three is enough","ABS")],
  target="'looks good' on THREE",deciding="Verify the instrument before trusting the reading.",rule="Test set → threshold → publish → deploy → label.",camo=[]),
 dict(concept="Whisper vs monitor vs barge",stem="A coach wants to hear a live call and speak to the agent without the customer hearing. Later, a director wants to join the call and speak to everyone. Which Genesys Cloud participant actions?",
  opts=[("Coach for the first; barge for the second. Monitor is silent listening only","KEY"),("Monitor for both","DROP"),("Barge for both","INV"),("Consult transfer for the first","CONF")],
  target="agent only vs EVERYONE",deciding="Who can hear the supervisor's voice.",rule="Monitor = hear. Coach = talk to agent only. Barge = talk to all.",camo=["director"]),
 dict(concept="Warm vs hot transfer",stem="An agent introduces the customer to a coach and stays on to hand over context. Another agent sends a threatening caller straight to a leadership queue. Which transfer types, in API terms?",
  opts=[("Consult transfer (warm) · blind transfer (hot)","KEY"),("Blind for both","DROP"),("Consult for both","DROP"),("Conference for the first, consult for the second","INV")],
  target="introduces vs STRAIGHT",deciding="Whether the sender stays on the line.",rule="Consult = warm, sender stays. Blind = hot, sender drops.",camo=[]),
 dict(concept="Carrying context on transfer",stem="Leadership answers a hot transfer and sees nothing about the case. What was missing?",
  opts=[("Conversation attributes (record number, whisper score) set before transfer, read by the screen-pop integration on the receiving side","KEY"),("A longer hold message","DROP"),("A knowledge article","CONF"),("Barge instead of transfer","INV")],
  target="sees NOTHING",deciding="Context travels as attributes on the conversation.",rule="Set attributes, then transfer; the pop reads them.",camo=[]),
 dict(concept="Real-time signal",stem="The whisper service needs to know the moment a call connects and every state change after, without polling every second. Which API pattern?",
  opts=[("Notifications API — a channel and WebSocket subscription to conversation topics","KEY"),("Polling the Conversations API each second","ADJ"),("Analytics API daily export","INV"),("A data table","CONF")],
  target="the MOMENT · without polling",deciding="Push over pull for live state.",rule="Notifications for now; Analytics for later.",camo=[]),
 dict(concept="Sentiment as a sequencer",stem="A manager proposes using the whisper score in quarterly reviews 'since we have it.' What is the correct position, and why does it matter to adoption?",
  opts=[("Scores sequence which calls a coach hears; they are non-determinative and never admissible in evaluation — set at launch so the floor trusts the whisper","KEY"),("Use it; more data is better","ABS"),("Use it only for top performers","ADJ"),("Delete the scores after each shift","INV")],
  target="'since we have it'",deciding="The trust contract is the adoption mechanism.",rule="Sequence, never evaluate.",camo=[]),
 dict(concept="Where the case state lives",stem="The IVR needs to know whether the caller has a case in Awaiting Customer. Which ServiceNow surface, and from where?",
  opts=[("Table API read on the case table filtered by the contact/account, called from an Architect data action","KEY"),("A knowledge article","CONF"),("The agent asks","DROP"),("Genesys external contacts","ADJ")],
  target="IVR needs to KNOW",deciding="Data actions call the record source of truth.",rule="Architect asks ServiceNow; ServiceNow answers from the table.",camo=[]),
 dict(concept="Intelligent IVR vs bot",stem="A vendor pitches a conversational bot to 'deflect 30%.' The design here deflects with lookups. What is the distinction that matters?",
  opts=[("A bot converses to discover intent; an intelligent IVR already knows the state from data and acts — fewer turns, no persona, measurable by re-contacts","KEY"),("They are the same","ABS"),("Bots are always better","ABS"),("IVRs cannot use data","ABS")],
  target="discover vs already KNOW",deciding="Data before dialogue.",rule="Deflection by knowledge, not by conversation.",camo=["30%"]),
 dict(concept="Proactive deflection",stem="A major incident affects thousands of customers. The IVR should tell affected callers before they queue and offer a callback when it is fixed. Which ServiceNow object and Genesys capability?",
  opts=[("Major incident / major case lookup by affected CI or account → Architect announcement → callback creation","KEY"),("A survey","CONF"),("An SLA","CONF"),("Barge","INV")],
  target="BEFORE they queue · when fixed",deciding="The parent record knows who is affected; callback holds the promise.",rule="Announce from the parent; callback on resolution.",camo=["thousands"]),
 dict(concept="Who is free to coach",stem="The whisper invite should go only to a coach who is not on a call and is on shift. Which Genesys data?",
  opts=[("Presence and routing status of users in the coaching group, plus utilization","KEY"),("Wrap-up codes","CONF"),("Evaluation forms","ADJ"),("Division","ADJ")],
  target="not on a call · on shift",deciding="Availability is presence × routing status × capacity.",rule="Ask the platform who is free; do not guess from a schedule.",camo=[]),
 dict(concept="Write-back",stem="After a whisper, nothing is recorded anywhere. Six months later nobody can say whether whispers helped. What should have been built?",
  opts=[("Write-back of every whisper event to the ServiceNow record (work note) and to the lake as a label, so outcomes train the threshold","KEY"),("A monthly survey of coaches","ADJ"),("Nothing; coaching is informal","ABS"),("A spreadsheet","DROP")],
  target="nobody can SAY",deciding="An executed action must produce telemetry.",rule="Every human decision is a label for the next machine decision.",camo=["six months"]),
 dict(concept="Permissions and scope",stem="A coach in one division can monitor calls in another division's queues. What is misconfigured?",
  opts=[("The coach's role is granted across divisions; scope the monitor/coach permission to the coach's division","KEY"),("Utilization","CONF"),("Wrap-up codes","CONF"),("The Notifications channel","ADJ")],
  target="ANOTHER division's queues",deciding="Permission × division = scope.",rule="Coaching permission follows the division boundary.",camo=[]),
 dict(concept="Hot-transfer triggers",stem="Which of the following should fire a hot transfer to leadership automatically, without a human deciding?",
  opts=[("None of them — hot transfer fires on explicit triggers (threat, legal, regulatory) or the agent's hot key, never on a sentiment score alone","KEY"),("Any call with negative sentiment","INV"),("Any call over ten minutes","ADJ"),("Any VIP","ADJ")],
  target="WITHOUT a human deciding",deciding="Scores sequence; humans decide.",rule="Automation routes attention; it does not seize the call.",camo=[]),
 dict(concept="Measuring deflection honestly",stem="Deflection is reported at 40%. Re-contacts within seven days doubled. What happened?",
  opts=[("The IVR deflected calls that needed a human; measure deflection net of re-contacts","KEY"),("Success — 40% is the target","INV"),("Customers prefer calling back","ABS"),("The SLA changed","CONF")],
  target="deflection UP · re-contacts UP",deciding="A deflected call that returns was not deflected.",rule="Deflection = served without a queue AND not back within seven days.",camo=["40%"]),
 dict(concept="Which side owns what",stem="Where does each piece of logic belong: the whisper threshold, the transfer action, the case state, the caller's pending question?",
  opts=[("Threshold: the scoring service (lake side) · transfer: Genesys · case state and pending question: ServiceNow · the IVR reads, never owns","KEY"),("Everything in Architect","DROP"),("Everything in ServiceNow","DROP"),("Everything in the bot","INV")],
  target="OWNS",deciding="Each system decides what it is the source of truth for.",rule="Server decides, client renders — three servers, one loop.",camo=[]),
 dict(concept="No new processor",stem="Security asks what new data leaves the environment for this design. What is the honest answer?",
  opts=[("Nothing new — Genesys and ServiceNow already exchange this data through existing integrations; the scoring runs on the existing lake; no new vendor, processor or egress","KEY"),("Audio goes to a new AI vendor","INV"),("Transcripts go to the coach's phone","INV"),("Unknown","ABS")],
  target="what NEW data leaves",deciding="Compose from what is already cleared.",rule="No new ingress or egress is the design constraint, not an afterthought.",camo=[]),
 ])
